'use client';

import { use, useEffect, useState } from 'react';
import type { CollectionNode } from '@rocket/types';
import { API_BASE } from '@/lib/api';

interface Docs {
  id: string;
  name: string;
  description: string | null;
  variables: { key: string; value: string }[];
  tree: CollectionNode[];
}

const METHOD_COLOR: Record<string, string> = {
  GET: '#3fb950',
  POST: '#d29922',
  PUT: '#58a6ff',
  PATCH: '#a371f7',
  DELETE: '#f85149',
};

export default function DocsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const [docs, setDocs] = useState<Docs | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch(`${API_BASE}/api/public/collections/${id}/docs`)
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error('Not public or not found'))))
      .then(setDocs)
      .catch((e) => setError(e.message));
  }, [id]);

  if (error)
    return <main style={{ padding: '3rem', color: 'var(--muted)' }}>This documentation is not available. {error}</main>;
  if (!docs) return <main style={{ padding: '3rem', color: 'var(--muted)' }}>Loading…</main>;

  return (
    <main style={{ maxWidth: 820, margin: '0 auto', padding: '3rem 1.5rem' }}>
      <h1 style={{ marginBottom: '0.25rem' }}>{docs.name}</h1>
      {docs.description && <p style={{ color: 'var(--muted)' }}>{docs.description}</p>}
      {docs.variables.length > 0 && (
        <section style={{ margin: '1.5rem 0' }}>
          <h3 style={{ fontSize: '0.95rem' }}>Variables</h3>
          <ul style={{ color: 'var(--muted)', fontSize: '0.85rem' }}>
            {docs.variables.map((v) => (
              <li key={v.key}>
                <code>{v.key}</code> = {v.value}
              </li>
            ))}
          </ul>
        </section>
      )}
      <DocNodes nodes={docs.tree} />
      <footer style={{ marginTop: '3rem', color: 'var(--muted)', fontSize: '0.8rem' }}>
        Generated by Rocket 🚀
      </footer>
    </main>
  );
}

function DocNodes({ nodes }: { nodes: CollectionNode[] }) {
  return (
    <>
      {nodes.map((node) =>
        node.type === 'folder' ? (
          <section key={node.id} style={{ marginTop: '1.5rem' }}>
            <h2 style={{ fontSize: '1.15rem', borderBottom: '1px solid var(--border)', paddingBottom: 4 }}>
              {node.name}
            </h2>
            <DocNodes nodes={node.children} />
          </section>
        ) : (
          <article
            key={node.id}
            style={{ border: '1px solid var(--border)', borderRadius: 8, padding: '0.9rem 1rem', marginTop: '0.75rem' }}
          >
            <div style={{ display: 'flex', gap: '0.6rem', alignItems: 'center' }}>
              <span style={{ color: METHOD_COLOR[node.request.method] ?? 'var(--muted)', fontWeight: 700, fontSize: '0.8rem' }}>
                {node.request.method}
              </span>
              <strong>{node.request.name}</strong>
            </div>
            <code style={{ color: 'var(--muted)', fontSize: '0.82rem', display: 'block', marginTop: 4 }}>
              {node.request.url}
            </code>
            {node.request.description && (
              <p style={{ fontSize: '0.85rem', marginBottom: 0 }}>{node.request.description}</p>
            )}
            {node.request.headers.filter((h) => h.enabled).length > 0 && (
              <div style={{ marginTop: '0.5rem', fontSize: '0.78rem', color: 'var(--muted)' }}>
                <strong>Headers:</strong>{' '}
                {node.request.headers.filter((h) => h.enabled).map((h) => h.key).join(', ')}
              </div>
            )}
          </article>
        ),
      )}
    </>
  );
}
